apiVersion: v1 
kind: Secret 
metadata: 
  name: my-secrets
  labels: 
    app: myapp
data: 
  mysql_user: YWRtaW4=
  mysql_password: YWRtaW4=
  mysql_root_password: cm9vdA==
  mysql_database: c3R1ZGVudGFwcA==
