apiVersion: v1 
kind: Pod 
metadata: 
  name: tainpod 
  labels: 
    app: myapp
spec: 
  tolerations: 
    - key: "prod"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers: 
    - name: nginx-container
      image: nginx:latest 
      ports: 
        - name: myport
          containerPort: 80